### ISSUE TITLE
Are you open to PR's?

### ISSUE THREAD

**Issue by zesoft23** [jselbie/wrekonline#9]
We're hoping to move some of the streaming + archive things in the next few months with our generic update. Do you still have the pipeline to update this app on the Play + Fdroid store? Happy to help of course!

We currently have 320kbps streams available now, and are hoping to ditch icecast and move to [HLS streaming](https://www.dacast.com/blog/hls-streaming-protocol/) sometime in the near future.

**Comment by jselbie** [comment]
Hi Jack,

Would love to have you help keep the app up to date.  Yes, we can still update the app via Google Play Store.  The bigger challenge is just getting the code to build again using either the original Android SDK it was built (19) with or a newer one.  I don't think it would be hard - just a necessary first step.

I'd like to hear more about your plans to move off of icecast and onto HLS.  The Android code might need some adjustments if the native Android Media Player control doesn't support HLS.

Do you have a link to the 320kbit/sec streams?  I didn't see it listed on wrek.org.

Follow up with me at:  john at selbie dot com
